ipaserver_domain: ipalab.local

ipaserver_realm: IPALAB.LOCAL

ipaserver_admin_password: 'SecureAdminPass1!'

ipaserver_dir_manager_password: 'SecureDMPass1!'

ipaadmin_password: 'SecureAdminPass1!'

ipadm_password: 'SecureDMPass1!'

ipaserver_ip: 192.168.1.128 # IP of your IPA server

nfs_export_dir: /home # Directory to export over NFS

nfs_server_ip: 192.168.1.128 # Same as IPA server in this lab

ipaserver_setup_dns: true

ipaserver_auto_forwarders: true

ipaserver_no_dnssec_validation: true
