[ipaserver]

ipa-server.example.com

[ipaclients]

ipa-client1.example.com

ipa-client2.example.com

ipa-client3.example.com

[nfsserver]

ipa-server.example.com # The IPA server also acts as NFS server in this lab

[lab:children]

ipaserver

ipaclients
