[ipaserver]

ipa-server.lab.ipa

[ipaclients]

ipa-client1.lab.ipa

ipa-client2.lab.ipa

ipa-client3.lab.ipa

[nfsserver]

ipa-server.lab.ipa # The IPA server also acts as NFS server in this lab

[lab:children]

ipaserver

ipaclients
