---
- name: Creating users
  hosts: ipaserver
  become: true
  vars_files:
    - ../group_vars/users_vault.yml
  tasks:
    - name: Add FreeIPA users
      freeipa.ansible_freeipa.ipauser:
        ipaadmin_password: "{{ ipaserver_admin_password }}"
        name: "{{ item.username }}"
        first: "{{ item.first }}"
        last: "{{ item.last }}"
        state: present
        password: "{{ item.password }}"
        update_password: on_create
        homedir: "{{ item.homedirectory }}"
      loop: "{{ ipa_users }}"

    - name: Create physical home directory on designated host
      ansible.builtin.file:
        path: "/home/{{ item.username }}"
        state: directory
        owner: "{{ item.username }}"
        group: "{{ item.username }}"
        mode: '0700'
      delegate_to: "{{ item.home_host }}"
      loop: "{{ ipa_users }}"
