---
- name: Using Roles
  hosts: ipaclients
  become: true

  tasks:
    - name: user nfs_server role
      ansible.builtin.include_role:
        name: nfs_server
        apply:
          tags: [nfs, storage]
      tags: [nfs, storage]
